version: "3.7"

services:
  flask:
    build: ./src
    container_name: src
    restart: always
    environment:
      - APP_NAME=src
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "5000:5000"
